name: Daily Commit

on:
  schedule:
    - cron: '0 7 * * *'   # каждый день в 7:00 утра UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Daily activity
        run: |
          echo "Daily activity on $(date)" >> activity.log
          git config user.name "swags1234"
          git config user.email "nikita-chernov-1994@yandex.ru"
          git add activity.log
          git commit -m "🤖 Daily activity: $(date)"
          git push
